### ISSUE TITLE
Content styles should not be in the theme and should not depend on variables

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-theme-lark#119]
Examples:

* image styles
* `<code>` styles
* ...

These should be in their respective packages and should not depend on CSS variables.

**Comment by oleq** [comment]
I remember that we also discussed how to separate content styles and UI styles. Because if we moved the image, code, etc. styles to their respective packages, still they will be tied to the editor (e.g. loaded by some `ImageUI` or whatever), which is not alright because developers should be able to:
1. use them in the frontend where the editor is not loaded,
2. drop them completely (for whatever the reason).

I'm wondering how to do that and if webpack can help us. What we could possibly do is another entry point JS which would load content styles only using the style-loader. Could that work? OTOH, that would require another `<script>` tag to insert CKEditor and could cause problems for the people including CKEditor in their applications. This problem looks tricky.

**Comment by Reinmar** [comment]
This is a separate issue. The ability to retrieve all content styles from the editor still requires these styles to be defined in the right place and to be independent of the theme.

So, let's first fix the problem with where these styles are and how they look (which we can do pretty quickly). And then we can start thinking whether we are able to expose content styles in any way (which will be rather hard and we may end up writing them down in the docs manually).

**Comment by Reinmar** [comment]
BTW, widget styles (focus outline, selection border) are not content styles to me. They are part of the editor's UI.
