### ISSUE TITLE
SplitButton's `isOn=true` state is barely visible.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-theme-lark#131]
The same goes for `actionView`:
![selection_032](https://user-images.githubusercontent.com/247363/35984583-0c435920-0cf5-11e8-8f30-178e7b474ebc.png)

and `arrowView`:
![selection_033](https://user-images.githubusercontent.com/247363/35984604-18e807fc-0cf5-11e8-8854-f9f2b0e3b1af.png)

**Comment by jodator** [comment]
Adding: 

```css
	& > .ck-button,
	& > * > .ck-button,
	& > * > * > .ck-button {
```

in https://github.com/ckeditor/ckeditor5-theme-lark/blob/7999134bef289f75e827d83b531e5b1aeaa71f22/theme/ckeditor5-ui/components/editorui/editorui.css#L39-L49

Fixes this but might be not the best solution:

![selection_034](https://user-images.githubusercontent.com/247363/35984833-87e12e4a-0cf5-11e8-9b59-e85e351f2de9.png)

**Comment by oleq** [comment]
The problem has been analyzed correctly. That's more or less what we're supposed to do.

But still that's a tricky one, I'm afraid. I've never liked this _Christmas Tree_ selectors but I couldn't come up with a better one. Ideas:

## Decentralization

We could move this logic to components/features – a drop-down would add such style and we could even provide a mixin for this (delivered by editorui). But then, these styles are not very useful, if someone decided to compile the theme without the `EditorUiView` (e.g. replaced with something else?). It's an upside-down approach anyway, a drop-down (child) understanding stuff about a hypothetical parent (toolbar). A no-go for me.

## Narrowing down

Instead of `& > * > * ...` we could simply put all use cases here like
```css
& > .ck-button,
& > .ck-dropdown > .ck-button,
& > .something-to-do-with-split-button > .ck-button {
```
There are not many of them. Would there be more (like much more)? I don't think so. It would also make more sense for developers decyphering this code because it clearly states what cases it covers.

LGTM

## Another class

A perfect solution would be a CSS class (e.g. `.ck-toolbar_button`) for such buttons to be styled. But honestly, I see absolutely no way to add it to a dropdown, which is hosted by the toolbar. A toolbar would need to know that its child's button (`div.ck-dropdown > .ck-button`) should get such class. How? No idea. But it would definitely be the most elegant approach.

cc @Reinmar

**Comment by jodator** [comment]
So it should be like this:

```css
& > .ck-button,
& > .ck-dropdown > .ck-button,
& > .ck-dropdown > .ck-splitbutton > .ck-button {
```

I'm fine with that as it is more clear what it does then _Xmas tree_ before.
