### ISSUE TITLE
Disable hover and active states for disabled button

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-theme-lark#14]
What do you think about disabling hover and active state for disabled button? Right now disabled button has lower opacity, and looks disabled, but still is reaction for hover and click:
![jun-22-2016 16-44-52](https://cloud.githubusercontent.com/assets/1057056/16271206/5cd57b84-3899-11e6-98ae-c870cdae81d7.gif)

I think we could prevent changing styles for hover and active on disabled button:
![jun-22-2016 16-48-30](https://cloud.githubusercontent.com/assets/1057056/16271275/a09e2fb4-3899-11e6-9a1e-660e65c237dd.gif)

**Comment by fredck** [comment]
For me it makes sense to remove it for hover state. It may be good for focus state though (keyboard navigation).

**Comment by pomek** [comment]
> Right now disabled button has lower opacity, and looks disabled, but still is reaction for hover and click

It works exactly the same as it should. The _disabled_ button doesn't have an attribute `disabled`. So, the button looks like disabled but behaves like enabled. I would say, the currently disabled buttons are rather like disabled-like than disabled.

The `disabled` attribute marks button as unavailable using both navigations - keyboard navigation and mouse navigation. 

Could we consider to introduce the `disabled` attribute for disabled buttons?

**Comment by oskarwrobel** [comment]
I think we don't use `disabled` attribute because `[disabled]` button can't be focused. But @oleq will know more about it.

**Comment by oleq** [comment]
Both disabled and enabled buttons must get focus to sustain certain accessibility level. Otherwise, people who use screen readers would not be able to reach disabled buttons using the keyboard and tell whether they're... disabled. Or whether they exist at all. This would be weird because from their point of view, the number of buttons (features) in the toolbar would change depending on the selection, while the truth is that its the state what changes, not the feature itself.

**Comment by oskarwrobel** [comment]
`disabled` attribute cooperates fine with `<form />` element. I mean `button[disabled]` will not submit (or reset in case of `button[type="reset"]`) form on click, and it works out of the box. I was a little confused when I've spotted that we can't use this native mechanism but we have to check `model.isEnabled` and do `event.preventDefault()` instead.

> This would be weird because from their point of view, the number of buttons (features) in the toolbar would change depending on the selection

Maybe `link` element will be better as toolbar button? Maybe is worth to consider separate form buttons and (I don't know how to call it) action buttons? Form buttons will be the real buttons but action buttons will be the link elements?

**Comment by oleq** [comment]
@Reinmar, could you chime in on this topic a bit?

**Comment by fredck** [comment]
I'm not sure we'll keep leaving the browser to control the keyboard navigation. Most likely, we'll go the v4 way, where we handle both the focus and keyboard navigation by custom code.

If the above is true, it means that we have to find a solution that takes the buttons out of the browser keyboard navigation list, just like we do in v4.

**Comment by fredck** [comment]
`<button type="button" [disabled="disabled"] tabindex="-1">`???

**Comment by Reinmar** [comment]
@oleq: I actually did in https://twitter.com/reinmarpl/status/773446620998402048 :D.

Anyway, I agree with Fred. Most likely there will be custom code for handling the keyboard. Questions that remain for now is how to style disabled buttons and how to disable them in HTML. I'd simply follow the CKE4's way here (at least for now) to not think on it too much. We'll work on a11y later on and then we can check whether CKE4's way is the right way to go.

**Comment by oleq** [comment]
My feeling is that HTML's "disabled" attribute makes more sense when filling in some web form because if something is disabled there, it should not bother people using screen readers and the such because the process is not usually repeated very often. 

However, when it comes to toolbars, which are used again and again and again, the important factor is predictability, which means the toolbar always "looks" the same to the user and the screen reader, no matter what the selection or other state of edited content is. I'd expect button X to be always 3rd when navigating the FOO toolbar, no matter the state of the 1st and the 2nd one. If we go with HTML's "disabled", the focus pattern will be broken all the time and could be very, very confusing.

Besides, what we've done in v4 in terms of a11y has been accepted and verified by lots of users and customers. It matters.

**Comment by fredck** [comment]
The `disabled` attribute should not block us on focusing the button by code anyway, so we should be ok to go with it.
