### ISSUE TITLE
Link highlight resembles the selection

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-theme-lark#159]
![image](https://user-images.githubusercontent.com/156149/37217305-7346c04c-23bd-11e8-8c6c-5203b07c42a0.png)

You have to think for second to understand what's selected here.

**Comment by oleq** [comment]
I'm for changing it to

```css
--ck-color-link-selected-background: hsl(201, 100%, 96%);
```
since this is not an a11y feature and we don't have to be super contrast-compliant in this case IMO.

![image](https://user-images.githubusercontent.com/1099479/37459277-dbae0d3c-2847-11e8-9177-0a7358d45dcd.png)


----

The outline that we added in https://github.com/ckeditor/ckeditor5-theme-lark/issues/155 causes some nasty bright line across the native selection. When disabled, it looks OK
![image](https://user-images.githubusercontent.com/1099479/37459390-28affa00-2848-11e8-91a4-fdaee3d74afb.png)

**Comment by Reinmar** [comment]
> since this is not an a11y feature and we don't have to be super contrast-compliant in this case IMO.

+1

**Comment by dkonopka** [comment]
> `--ck-color-link-selected-background: hsl(201, 100%, 96%);`

👍 

> When disabled, it looks OK

So we should drop `outline` solution, and try proposed.
```css 
box-shadow: 0 0 0 1px var(--ck-color-link-selected-background);
```

Current outline:
![screen shot 2018-03-19 at 11 43 03](https://user-images.githubusercontent.com/10219857/37591176-ec200064-2b6a-11e8-8e23-ae88c3941f5d.png)

Box-shadow solution:
![screen shot 2018-03-19 at 11 44 19](https://user-images.githubusercontent.com/10219857/37591185-f7cefa00-2b6a-11e8-83b0-ad70f5450806.png)

**Comment by oleq** [comment]
I used the highlight color that I proposed with the box-shadow. WDYT?

<img width="492" alt="screen shot 2018-03-22 at 10 59 55" src="https://user-images.githubusercontent.com/1099479/37763768-3ae273ec-2dc0-11e8-8cf0-c615819e1928.png">

**Comment by Reinmar** [comment]
In this screenshot, it looks a bit too light for me, but I guess that the best way to find out whether it works in real life is to see it live :)
